apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devopsdays
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: apps/
    repoURL: 'https://github.com/rudzm/management.git'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true