deployment:
  replicaCount: 1
  image:
    repository: google/cloud-sdk
    pullPolicy: Always
    tag: "alpine"
  fullnameOverride: "bucket-app"

  serviceAccount:
    create: true
    workloadIdentity: true
    automount: true
    name: "bucket-app-sa"

  livenessProbe:

  readinessProbe:

  ingress:
    enabled: false

  autoscaling:
    enabled: false

  configMap:
    enabled: true
    data:
      BUCKET_NAME: gitops-show-app1-bucket

  commandOverwrite: 
    enabled: true
    cmd: ["/bin/bash"]
    args:
      - -c
      - >
        while true;
          do
            echo Welcome to Cloud Native Warsaw $(date +%m-%d-%Y-%M)
            # touch $(date +%m-%d-%Y-%M);
            # gsutil cp $(date +%m-%d-%Y-%M) gs://$BUCKET_NAME;
            sleep 90;
          done

bucket:
  name: gitops-show-app1-bucket
  location: us-central1
  storageClass: Standard
  # storageClass: Nearline
  deletionPolicy: Delete
  annotations: {}
  labels: {}
  iam:
    enabled: true
    member: bucket-app-sa
    role: roles/storage.admin

serviceaccount:
  name: bucket-app-sa
  annotations: {}
  labels: {}


