deployment:
  replicaCount: 1
  image:
    repository: eu.gcr.io/ab-security-dev/gitlab/google/google/cloud-sdk
    pullPolicy: Always
    tag: "437.0.1"
  fullnameOverride: "bucket-app"

  serviceAccount:
    create: true
    workloadIdentity: true
    automount: true
    name: "gitops-bucket-sa"

  livenessProbe:

  readinessProbe:

  ingress:
    enabled: false

  autoscaling:
    enabled: false

  configmaps:
    - name: configmap
      enabled: true
      directKeyValues:
        BUCKET_NAME: ab-gitops-bucket-app

  cmdOverwrite: true
  command: ["/bin/bash"]
  args:
    - -c
    - >
      while true;
        do
          # echo $(date +%m-%d-%Y-%M)
          touch $(date +%m-%d-%Y-%M);
          gsutil cp $(date +%m-%d-%Y-%M) gs://$BUCKET_NAME;
          sleep 90;
        done

bucket:
  name: ab-gitops-bucket-app
  location: europe-west2
  storageClass: Standard
  deletionPolicy: Delete
  annotations: {}
  labels: {}
  iam:
    enabled: true
    member: gitops-bucket-sa
    role: roles/storage.admin

serviceaccount:
  name: gitops-bucket-sa
  annotations: {}
  labels: {}


